### ISSUE TITLE
Initial implementation based on libreoffice conversation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/files_emfviewer#1]
## Feature request

As a Nextcloud user I want to view the contents of a EMF files. These might be sent via an email, so I open them with Viewer in Mail, or they are shared via Nextcloud Files and I open them with Viewer as well.

## Implementation

A .emf (`application/octet-stream`) file can't just be opened by the browser, but it can be converted to a viewable representation. Libreoffice can convert these with `libreoffice --headless --convert-to png input.emf`. This Nextcloud app can add a simple route to which a EMF file can be sent and converted. Sending the file makes the feature usable for attachments in Mail and also files on DAV.

## Work packages

* [x] https://github.com/nextcloud/viewer/issues/2008
* [ ] Create an endpoint for the conversation
* [ ] Extend viewer with a new handler but reuse the existing image handler
* [ ] Documentation
  * Requirements: libreoffice installation

**Comment by ChristophWurst** [comment]
This is done via https://github.com/nextcloud/viewer/pull/2065, https://github.com/nextcloud/server/pull/41395 and https://github.com/nextcloud/richdocuments/pull/3303
